### ISSUE TITLE
custom property using artifactory jenkins plugin

### ISSUE THREAD

**Issue by an-sush** [JFrogDev/project-examples#115]
Hello,
I am using Artifactory plugin 2.14.0 and having trouble setting custom properties to the published artifact:

```
def server = Artifactory.newServer url: "https://${baseArtURL}/artifactory", username: "${user}", password: "${password}"
def artifactoryDocker = Artifactory.docker server: server
artifactoryDocker.addProperty("artifactory-url", "${baseArtURL}").addProperty("status", "qa-passed").addProperty("commitId", "${env.GIT_COMMIT}")
def buildInfo = artifactoryDocker.push "docker-dev.${baseArtURL}/${dockerTag}", "docker-dev"
echo buildInfo.env.vars['status']
buildInfo.env.vars['next-stage'] = 'perf-test'
echo buildInfo.env.vars['next-stage']
server.publishBuildInfo buildInfo
```

Both the echo's print null and I am unable to see these properties in Artifactory console/explorer view also. Am I doing anything wrong?

**Comment by iyungsakrim** [comment]
sip

**Comment by iyungsakrim** [comment]
sip

**Comment by kerrhome** [comment]
Did you ever figure this out @an-sush ?

**Comment by an-sush** [comment]
@kerrhome No.. but as a workaround, I called the rest endpoint to set custom property

**Comment by kerrhome** [comment]
OK, I figured it what my problem was.  Thanks for the reply @eyalbe4!  Is there a website available that can tell me all of the methods (like Artifactory.docker.addProperty and buildInfo.capture etc) available to rtDocker (Artifactory.docker)?  My Google skills aren't finding it.  I was wondering if there is a "replaceProperty" method available.  Also, ffter having used Jenkins pipeline's docker.build to build the docker image from a Dockerfile, I used rtDocker.push to push it, but I'm unable to pick up the build environment information for publishBuildInfo via buildInfo.env.capture = true.  Using the rtDocker + buildInfo seems to be different from fileUploadSpec + buildInfo (as far as capturing info and linking builds etc and artifacts in Artifactory), but it could just be user error.

**Comment by an-sush** [comment]
Thankyou @eyalbe4 . I will try with latest artifactoyr plugin [2.16.2](https://plugins.jenkins.io/artifactory)

**Comment by adiallot** [comment]
im using plugin 3.0.0
im trying too to configure addProperty with env vraible and getting error:

configuration:
 env.JENKINS_VERSION = sh(returnStdout: true, script: "docker image inspect ${tagName} |grep JENKINS_VERSION | sed 's/\"JENKINS_VERSION=//g' |sed 's/\",//g' | sed '\$!N; /^\\(.*\\)\\n\\1\$/!P; D\' | sed 's/ //g' ")

 rtDocker.addProperty("jenkins_version", "${env.JENKINS_VERSION}")

error:
hudson.remoting.ProxyException: groovy.lang.MissingMethodException: No signature of method: org.jfrog.hudson.pipeline.common.types.Docker.addProperty() is applicable for argument types: (java.lang.String, org.codehaus.groovy.runtime.GStringImpl) values: [jenkins_version, 2.161
]
Possible solutions: addProperty(java.lang.String, [Ljava.lang.String;), hasProperty(java.lang.String)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:153)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:155)
