### ISSUE TITLE
with the bash deploy-file.sh my artifacts are published but build-info gives errors

### ISSUE THREAD

**Issue by bbaassssiiee** [JFrogDev/project-examples#25]
ERROR: Could not publish build-info: Error occurred while requesting version information: Unauthorized
java.io.IOException: Could not publish build-info: Error occurred while requesting version information: Unauthorized
	at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.sendBuildInfo(ArtifactoryBuildInfoClient.java:244)
	at org.jfrog.hudson.generic.GenericBuildInfoDeployer.deploy(GenericBuildInfoDeployer.java:62)
	at org.jfrog.hudson.generic.ArtifactoryGenericConfigurator$1.tearDown(ArtifactoryGenericConfigurator.java:309)
	at hudson.model.Build$BuildExecution.doRun(Build.java:173)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
Warning: you have no plugins providing access control for builds, so falling back to legacy behavior of permitting any downstream builds to be triggered

**Comment by alishahbaz111** [comment]
Were you able to figure this out?

**Comment by bbaassssiiee** [comment]
Yeah, ENV vars to the rescue.
