### ISSUE TITLE
Error in msbuild sample

### ISSUE THREAD

**Issue by sudgopal** [JFrogDev/project-examples#47]
Hi -

When I try to re-build the "ms-build" example project , I encounter the following issues. Can you please help in moving forward?

Could not extract targetBuilderCallback from Microsoft.Build.BackEnd.TaskHost
   at JFrog.Artifactory.BuildEngineExtensions.GetProjectInstance(IBuildEngine buildEngine)
   at JFrog.Artifactory.BuildEngineExtensions.GetEnvironmentVariable(IBuildEngine buildEngine, String key, Boolean throwIfNotFound)
   at JFrog.Artifactory.Utils.SolutionHandler.MsbuildInterpreter(FileInfo artifactoryConfigurationFile, ArtifactoryBuild task)
   at JFrog.Artifactory.Utils.SolutionHandler.GetMainConfiguration()
   at JFrog.Artifactory.Utils.SolutionHandler..ctor(ArtifactoryBuild task, BuildInfoLog log)
   at JFrog.Artifactory.ArtifactoryBuild.Execute()	Artifactory			

The "ArtifactoryBuild" task failed unexpectedly.
System.Exception: Exception from Artifactory Task: Could not extract targetBuilderCallback from Microsoft.Build.BackEnd.TaskHost
   at JFrog.Artifactory.ArtifactoryBuild.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Artifactory

**Comment by eyalbe4** [comment]
@sudgopal,
Are you using Artifactory-Pro? Which .NET Framework are you using?

**Comment by sudgopal** [comment]
I am using Artifactory - OSS version with .NET Framework 4.6.1

**Comment by sudgopal** [comment]
I am facing similar issue in Artifactory-Pro version too. could you please help? Thanks.

**Comment by eyalbe4** [comment]
@sudgopal,
We'd like to help you resolve this issue. Please send an email with all the details to support@jfrog.com and we'll help you pinpoint the root cause of the issue. Please make sure to include your Artifactory-Pro version and a sample project that demonstrates the issue.

**Comment by stevez** [comment]
I have the same issue, looks like it is known issue after a year

**Comment by eyalbe4** [comment]
From the exception, it looks like the plugin could not read / find the the configuration in the solution files. This could indicate an issue with applying the plugin on the solution.
@sudgopal, were you able to resolve the issue a few months ago?
I also see the issue discussed [here](https://stackoverflow.com/questions/39764673/msbuild-artifactory-plugin-build-error)
