### ISSUE TITLE
NullPointerException server.upload

### ISSUE THREAD

**Issue by rajholla** [JFrogDev/project-examples#56]
upload throws a null pointer exception.
Both target & pattern location are accurate.

 node('docker-maven-slave') {
def server = Artifactory.server('143@143')
		def uploadSpec = """{
					"files": [
							{
								"pattern": "/home/jenkins/.m2/repository/com/org/mytestapp/webmodule/1.0.1-SNAPSHOT/*war",
								"target": "ORG-Snapshots/com/org/mytestapp/webmodule/1.0.1-SNAPSHOT/"
							}
								]
							}"""
		def buildInfo = server.upload(uploadSpec)
		server.publishBuildInfo(buildInfo)
		}
Thank you for your time !

**Comment by romangurevitch** [comment]
@rajholla, thanks for reporting this.
Could you add the stack trace of the build?

**Comment by rajholla** [comment]
@romangurevitch ,Thank you for your time.

After collecting the entire stack below,I was able to pin down the issue.Upgrading my plugin version from 2.5.1 to 2.7.2 resolved the issue.

java.lang.NullPointerException
	at com.cloudbees.plugins.credentials.matchers.IdMatcher.<init>(IdMatcher.java:49)
	at com.cloudbees.plugins.credentials.CredentialsMatchers.withId(CredentialsMatchers.java:111)
	at org.jfrog.hudson.util.plugins.PluginsUtils.credentialsLookup(PluginsUtils.java:61)
	at org.jfrog.hudson.CredentialsConfig.provideUsername(CredentialsConfig.java:68)
	at org.jfrog.hudson.pipeline.executors.GenericDownloadExecutor.downloadArtifacts(GenericDownloadExecutor.java:69)
	at org.jfrog.hudson.pipeline.executors.GenericDownloadExecutor.execution(GenericDownloadExecutor.java:52)
	at org.jfrog.hudson.pipeline.steps.DownloadStep$Execution.run(DownloadStep.java:60)
	at org.jfrog.hudson.pipeline.steps.DownloadStep$Execution.run(DownloadStep.java:44)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousStepExecution.start(AbstractSynchronousStepExecution.java:40)

It would be very helpful if you could answer below questions. 

How do we get time stamped snapshots uploaded ? this appears to be the default behavior when using Artifactory plugin with freestyle job.
Also when using Artifactory plugin with freestyle job there is no need to mention the entire artifactory repository path like "ORG-Snapshots/com/org/mytestapp/webmodule/1.0.1-SNAPSHOT/" instead by just mentioning "ORG-Snapshots" enough to upload in the correct location. Is this possible to achieve this in pipeline ?? 

Again ,Thank you for your time !
